accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name = "signup"),
    path("login/", views.sign_in, name = "signin"),
    path("logout/", views.logout_view, name = "logout"),
]

admins/urls.py
#from django.conf.urls import url
from django.urls import path
from . import views

app_name = "admins"

urlpatterns = [
    path("", views.index, name = "admin_index"),
]

mainsite/urls.py
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
"""
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Login Administrator"
admin.site.site_title = "Food-Ordering"
admin.site.index_title = "Food Ordering Admin Site"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

from django.contrib import admin
from django.urls import path, include
#from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "home"),
    path('accounts/', include("accounts.urls")),
    path('profile/', include("profiles.urls")),
    path('admins/', include("admins.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Change Site Title, Index Title and Site Title
admin.site.site_header = "Bank of Indonesia"
admin.site.site_title = "Bank of Indonesia"
admin.site.index_title = "Welcome to Bank of Indonesia Panel"

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Banking System</title>

        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        {% block stylecontent %}
        {% endblock %}

        <link rel="stylesheet" href="/static/common-styles.css">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
            <a class="navbar-brand">Bank of Indonesia</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'home' %}" id="nav-home">Home</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" id="nav-create">Create new account</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signin' %}" id="nav-login">Sign In</a>
                </div>
            </div>
            <div class="container text-right">
            <a>&copy; Website created with &hearts; by:</a>
            </div>
            <div class="container text-center">
            <a href="https://postgrethon.wordpress.com" target="_blank">Postgrethon</a>
            </div>
        </nav>

        <br> <br> <br>

        {% block bodycontent %}
        {% endblock %}

        {% block scriptcontent %}
        {% endblock %}

        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </body>
</html>

templates/index.html
{% extends 'base_layout.html' %}

{% block stylecontent %}
    <style>
        h1 {
            border-bottom: 1px solid;
        }
        h4 {
            font-weight: 400;
        }
        a:hover {
            text-decoration: none;
        }

        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>
{% endblock %}


{% block bodycontent %}
        <div class="container text-center">
        <h1>STATUS AND POSITION OF BANK OF INDONESIA</h1>
        </div>

        <div class="container text-left">
        <p>
            An Independent State Institution

            A new chapter in the history of Bank Indonesia as an independent central bank was ushered in on 17th May 1999 when the Bank Indonesia Act (No. 23 of 1999) was enacted, which has subsequently been amended by Act No.6 of 2009. The BI Act confers status and position as an independent state institution, free from interference by the Government and/or other parties, unless explicitly stipulated in prevailing laws.
            In accordance with the BI Act, Bank Indonesia is a fully autonomous state institution in terms of formulating and implementing its duties and responsibilities.  Furthermore, Bank Indonesia has a duty to reject or disregard any attempt of intervention or interference by any party, while external parties have no grounds or justification to interfere with task implementation at Bank Indonesia.
            The special status and position conferred are necessary to ensure Bank Indonesia can effectively and efficiently implement its role and function as the monetary authority.

            As a Legal Entity
            Bank Indonesia’s status as a public legal entity or civil legal entity is explicitly stipulated in prevailing laws.  As a public legal entity and in accordance with its duties and responsibilities, Bank Indonesia is authorised to issue legally binding regulations in the implementation of the law.  As a civil legal entity, Bank Indonesia is authorised to represent itself within and outside a court of law.​
        </p>
        </div>

        <div class="container text-center">
            <h4><em>Vision and Mission</em></h4>
        </div>

        <div class="container text-left">
        <p>
            Vision<br>
            To become the foremost digital central bank that creates tangible contribution to the national economy and be the best central bank amongst emerging market countries towards an Advanced Indonesia.<br>
            <br>
            Mission<br>
            To achieve and maintain Rupiah stability through effective monetary policy and Bank Indonesia policy mix.<br>
            To engage in maintaining financial system stability through effective macro-prudential policy in synergy with micro-prudential policy by the Financial Services Authority (OJK).<br>
            To engage in developing digital economy and finance through strengthening Bank Indonesia payment system policy in synergy with the government and other strategic partners policies.<br>
            To support macroeconomic stability and sustainable economic growth through achieving synergy among Bank Indonesia’s policy mix, Government’s fiscal policies and structural reformation as well as other strategic partners policies.<br>
            To engage in enhancing financial market deepening in order to strengthen the effectiveness of Bank Indonesia policy and to support national economic financing.<br>
            To develop sharia economy and finance from the national level to the regional level.<br>
            To build a digital-based central bank in terms of the policies and institutional arrangements by strengthening the organisation, human resource, governance and reliable information system as well as proactive international role.<br>
        </p>
        </div>
    <br><br>
{% endblock %}